export const DEFAULT_CATEGORY_OPTIONS = [
  { value: "blog-category-1", label: "Restoran" },
  { value: "blog-category-2", label: "Otel" },
  { value: "blog-category-3", label: "Araç Kiralama" },
  { value: "blog-category-4", label: "Alışveriş" },
  { value: "blog-category-5", label: "Eğlence" },
  { value: "blog-category-6", label: "Plaj" },
  { value: "blog-category-7", label: "Müze" },
  { value: "blog-category-8", label: "Tarihi Yerler" },
  { value: "blog-category-9", label: "Spor" },
  { value: "blog-category-10", label: "Kültür" },
  { value: "blog-category-11", label: "Abu Dhabi" },
  { value: "blog-category-12", label: "Abu Dhabi City Tour" },
  { value: "blog-category-13", label: "Abu Dhabi Hotel" },
  { value: "blog-category-14", label: "Abu Dhabi Hotels" },
  { value: "blog-category-15", label: "Activities" },
  { value: "blog-category-16", label: "Adventure" },
  { value: "blog-category-17", label: "Aquaventure Waterpark" },
  { value: "blog-category-18", label: "Bollywood Parks Dubai" },
  { value: "blog-category-19", label: "Burj Khalifa" },
  { value: "blog-category-20", label: "Cafes" },
  { value: "blog-category-21", label: "Cafes & Restaurant" },
  { value: "blog-category-22", label: "City Tours" },
  { value: "blog-category-23", label: "Cultural Museums" },
  { value: "blog-category-24", label: "Desert Safari" },
  { value: "blog-category-25", label: "Dubai" },
  { value: "blog-category-26", label: "Dubai Activities" },
  { value: "blog-category-27", label: "Dubai City Tour" },
  { value: "blog-category-28", label: "Dubai Family Activities" },
  { value: "blog-category-29", label: "Dubai Frame" },
  { value: "blog-category-30", label: "Dubai Hotel" },
  { value: "blog-category-31", label: "Dubai Hotels" },
  { value: "blog-category-32", label: "Dubai Luxury Shopping" },
  { value: "blog-category-33", label: "Dubai Miracle Garden" },
  { value: "blog-category-34", label: "Dubai Museums" },
  { value: "blog-category-35", label: "Dubai Parks and Resorts" },
  { value: "blog-category-36", label: "Dubai Shopping" },
  { value: "blog-category-37", label: "Dubai Shopping Guide" },
  { value: "blog-category-38", label: "Dubai Shopping Malls" },
  { value: "blog-category-39", label: "Dubai Theme Parks" },
  { value: "blog-category-40", label: "Dubai Travel Guide" },
  { value: "blog-category-41", label: "Dubai Visa" },
  { value: "blog-category-42", label: "Family Activities" },
  { value: "blog-category-43", label: "Family Activity" },
  { value: "blog-category-44", label: "Global Village" },
  { value: "blog-category-45", label: "Hotels" },
  { value: "blog-category-46", label: "IMG Worlds of Adventure" },
  { value: "blog-category-47", label: "JetCar" },
  { value: "blog-category-48", label: "Legoland Dubai" },
  { value: "blog-category-49", label: "Miracle Garden" },
  { value: "blog-category-50", label: "Motiongate Dubai" },
  { value: "blog-category-51", label: "Museum of the Future" },
  { value: "blog-category-52", label: "Museums" },
  { value: "blog-category-53", label: "Rent a Car" },
  { value: "blog-category-54", label: "Rent a Yacht" },
  { value: "blog-category-55", label: "Rent a Yatch" },
  { value: "blog-category-56", label: "Restaurants" },
  { value: "blog-category-57", label: "Riverland Dubai" },
  { value: "blog-category-58", label: "Shopping" },
  { value: "blog-category-59", label: "Theme Parks" },
  { value: "blog-category-60", label: "Uncategorized" },
  { value: "blog-category-61", label: "Wild Wadi Waterpark" },
];
