// prettier-ignore
export const DEFAULT_CATEGORY_OPTIONS = [
  { value: "category-restaurant", label: "Restoran" },
  { value: "category-hotel", label: "Otel" },
  { value: "category-car-rental", label: "Araç Kiralama" },
  { value: "category-shopping", label: "Alışveriş" },
  { value: "category-entertainment", label: "Eğlence" },
  { value: "category-beach", label: "Plaj" },
  { value: "category-museum", label: "Müze" },
  { value: "category-historical-places", label: "Tarihi Yerler" },
  { value: "category-sports", label: "Spor" },
  { value: "category-culture", label: "Kültür" },
  { value: "category-abu-dhabi", label: "Abu Dhabi" },
  { value: "category-abu-dhabi-city-tour", label: "Abu Dhabi City Tour" },
  { value: "category-abu-dhabi-hotel", label: "Abu Dhabi Hotel" },
  { value: "category-abu-dhabi-hotels", label: "Abu Dhabi Hotels" },
  { value: "category-activities", label: "Activities" },
  { value: "category-adventure", label: "Adventure" },
  { value: "category-aquaventure-waterpark", label: "Aquaventure Waterpark" },
  { value: "category-bollywood-parks-dubai", label: "Bollywood Parks Dubai" },
  { value: "category-burj-khalifa", label: "Burj Khalifa" },
  { value: "category-cafes", label: "Cafes" },
  { value: "category-cafes-restaurants", label: "Cafes & Restaurants" },
  { value: "category-city-tours", label: "City Tours" },
  { value: "category-cultural-museums", label: "Cultural Museums" },
  { value: "category-desert-safari", label: "Desert Safari" },
  { value: "category-dubai", label: "Dubai" },
  { value: "category-dubai-activities", label: "Dubai Activities" },
  { value: "category-dubai-city-tour", label: "Dubai City Tour" },
  { value: "category-dubai-family-activities", label: "Dubai Family Activities" },
  { value: "category-dubai-frame", label: "Dubai Frame" },
  { value: "category-dubai-hotel", label: "Dubai Hotel" },
  { value: "category-dubai-hotels", label: "Dubai Hotels" },
  { value: "category-dubai-luxury-shopping", label: "Dubai Luxury Shopping" },
  { value: "category-dubai-miracle-garden", label: "Dubai Miracle Garden" },
  { value: "category-dubai-museums", label: "Dubai Museums" },
  { value: "category-dubai-parks-and-resorts", label: "Dubai Parks and Resorts" },
  { value: "category-dubai-shopping", label: "Dubai Shopping" },
  { value: "category-dubai-shopping-guide", label: "Dubai Shopping Guide" },
  { value: "category-dubai-shopping-malls", label: "Dubai Shopping Malls" },
  { value: "category-dubai-theme-parks", label: "Dubai Theme Parks" },
  { value: "category-dubai-travel-guide", label: "Dubai Travel Guide" },
  { value: "category-dubai-visa", label: "Dubai Visa" },
  { value: "category-family-activities", label: "Family Activities" },
  { value: "category-family-activity", label: "Family Activity" },
  { value: "category-global-village", label: "Global Village" },
  { value: "category-hotels", label: "Hotels" },
  { value: "category-img-worlds-of-adventure", label: "IMG Worlds of Adventure" },
  { value: "category-jetcars", label: "JetCars" },
  { value: "category-legoland-dubai", label: "Legoland Dubai" },
  { value: "category-miracle-garden", label: "Miracle Garden" },
  { value: "category-motiongate-dubai", label: "Motiongate Dubai" },
  { value: "category-museum-of-the-future", label: "Museum of the Future" },
  { value: "category-museums", label: "Museums" },
  { value: "category-rent-a-car", label: "Rent a Car" },
  { value: "category-rent-a-yacht", label: "Rent a Yacht" },
  { value: "category-rent-a-yatch", label: "Rent a Yatch" },
  { value: "category-restaurants", label: "Restaurants" },
  { value: "category-riverland-dubai", label: "Riverland Dubai" },
  { value: "category-theme-parks", label: "Theme Parks" },
  { value: "category-uncategorized", label: "Uncategorized" },
  { value: "category-wild-wadi-waterpark", label: "Wild Wadi Waterpark" },
];
