export const DEFAULT_TAG_OPTIONS = [
  { value: "tag-economy", label: "Ekonomik" },
  { value: "tag-luxury", label: "Lüks" },
  { value: "tag-family", label: "Aile Dostu" },
  { value: "tag-romantic", label: "Romantik" },
  { value: "tag-beautiful", label: "Manzaralı" },
  { value: "tag-sea", label: "Denize Yakın" },
  { value: "tag-central", label: "Merkezi Konum" },
  { value: "tag-new", label: "Yeni" },
  { value: "tag-popular", label: "Popüler" },
  { value: "tag-recommended", label: "Önerilen" },
  { value: "tag-adventure", label: "Macera Dolu" },
  { value: "tag-cultural", label: "Kültürel" },
  { value: "tag-outdoor", label: "Açık Hava" },
  { value: "tag-indoor", label: "Kapalı Mekan" },
  { value: "tag-kid-friendly", label: "Çocuk Dostu" },
  { value: "tag-shopping", label: "Alışveriş Cenneti" },
  { value: "tag-active", label: "Yüksek Aktivite" },
  { value: "tag-religious", label: "Dinlendirici" },
  { value: "tag-photogenic", label: "Fotoğrafik" },
  { value: "tag-nightlife", label: "Gece Hayatı" },
  { value: "tag-easy-access", label: "Ulaşımı Kolay" },
  { value: "tag-seasonal", label: "Sezonluk" },
  { value: "tag-vip", label: "VIP Hizmet" },
  { value: "tag-group", label: "Grup Aktivitesi" },
  { value: "tag-food", label: "Yemek Odaklı" },
];
