export const DEFAULT_TAG_OPTIONS = [
  { value: "blog-tag-1", label: "Ekonomik" },
  { value: "blog-tag-2", label: "Lüks" },
  { value: "blog-tag-3", label: "Aile Dostu" },
  { value: "blog-tag-4", label: "Romantik" },
  { value: "blog-tag-5", label: "Manzaralı" },
  { value: "blog-tag-6", label: "Denize Yakın" },
  { value: "blog-tag-7", label: "Merkezi Konum" },
  { value: "blog-tag-8", label: "Yeni" },
  { value: "blog-tag-9", label: "Popüler" },
  { value: "blog-tag-10", label: "Önerilen" },
  { value: "blog-tag-11", label: "Macera Dolu" },
  { value: "blog-tag-12", label: "Kültürel" },
  { value: "blog-tag-13", label: "Açık Hava" },
  { value: "blog-tag-14", label: "Kapalı Mekan" },
  { value: "blog-tag-15", label: "Çocuk Dostu" },
  { value: "blog-tag-16", label: "Alışveriş Cenneti" },
  { value: "blog-tag-17", label: "Yüksek Aktivite" },
  { value: "blog-tag-18", label: "Dinlendirici" },
  { value: "blog-tag-19", label: "Fotoğrafik" },
  { value: "blog-tag-20", label: "Gece Hayatı" },
  { value: "blog-tag-21", label: "Ulaşımı Kolay" },
  { value: "blog-tag-22", label: "Sezonluk" },
  { value: "blog-tag-23", label: "VIP Hizmet" },
  { value: "blog-tag-24", label: "Grup Aktivitesi" },
  { value: "blog-tag-25", label: "Yemek Odaklı" },
];
