const DummyText = `
<h1 style="text-align: center">Dubai Şehrinde Gezilecek Yerler: Hayalinizdeki Tatili Stil ve Macera ile Planlayın</h1>
<figure class="enhanced-image" src="https://images.project-test.info/1.webp" alt="Görsel" size="fullscreen" alignment="center" objectfit="cover" caption="Dubai ile ilgili açıklama metni.">
  <img src="https://images.project-test.info/1.webp" alt="Görsel">
  <figcaption>Dubai ile ilgili açıklama metni.</figcaption>
</figure>
<p>Dubai'ye gitmeye değer mi? <u style="text-decoration-color: rgb(41, 199, 88); text-decoration-style: wavy; text-decoration-thickness: 3px; text-underline-offset: 3px">Seyahatseverler</u> için <span style="background-color: rgb(255, 255, 255); color: rgb(251, 43, 55); padding: 0.2rem 0.3rem; border-radius: 9999px; border: 2px solid rgb(251, 43, 55)">bir destinasyon</span> arayanlara <s style="text-decoration-color: rgb(255, 111, 97); text-decoration-style: wavy; text-decoration-thickness: 2px">geleceğin mimarisi</s>, <a target="_blank" rel="noopener" href="https://guideofdubai.com/toursandtickets"><u style="text-decoration-color: ; text-decoration-style: ; text-decoration-thickness: ; text-underline-offset: ">lüks deneyimler</u></a> ve nefes kesici doğal güzellikler sunan bir şehir olarak cevabımız kesinlikle evet. Dubai'nin yenilik ve zarafetini en iyi görebileceğiniz yerlerden biri, <em>The View Palm</em> adlı, <span style="background-color: rgb(240, 249, 255); color: rgb(12, 74, 110); padding: 0.4rem 0.6rem; border-radius: 0.3rem; border: 1px solid rgb(14, 165, 233)">Palm</span> Tower'ın 52. katında yer alıyor. Buradan ziyaretçiler, Palm Jumeirah'ın tam şeklini ve huzurlu Arap Körfezi'ni izleyebilirler.</p>
<p></p>
<div data-alert-box="" data-type="danger" data-title="Başlık">Merhaba bu bir uyarı.</div>
<hr>
<div data-alert-box="" data-type="information" data-title="">Merhaba bu başlıksız bir bilgi <a target="_blank" rel="noopener" href="https://www.theviewpalm.ae/?utm_source=GMBlisting&amp;utm_medium=organic&amp;utm_campaign=gmb"><u style="text-decoration-color: ; text-decoration-style: ; text-decoration-thickness: ; text-underline-offset: ">The View Palm</u></a> sadece bir seyir terası değil—Dubai'nin ruhunu yakalayan etkileyici bir deneyimdir. Bu panoramik platform, şehrin doğa ve insan tasarımı arasındaki uyumunu gözler önüne seriyor ve Dubai'de <a target="_blank" rel="noopener" href="https://guideofdubai.com/tour/dubai-iconic-places-tour"><u style="text-decoration-color: ; text-decoration-style: ; text-decoration-thickness: ; text-underline-offset: ">mutlaka görülmesi gereken yerlerden</u></a> biri olmasını sağlıyor.</div>
<p></p>
<h3>240 Metre Yükseklikten Eşsiz Bir Bakış</h3>
<p>Palm Jumeirah'ın kalbinde yer alan <a target="_blank" rel="noopener" href="https://www.theviewpalm.ae/?utm_source=GMBlisting&amp;utm_medium=organic&amp;utm_campaign=gmb"><u style="text-decoration-color: ; text-decoration-style: ; text-decoration-thickness: ; text-underline-offset: ">The View Palm</u></a> sadece fotoğraf çekmek için bir yer değil. Burası, Dubai'nin ikonik kıyı düzenine bir yolculuk sunuyor. İster tek başınıza, ister çift olarak, ister ailenizle ziyaret edin, burası kesinlikle <a target="_blank" rel="noopener" href="https://guideofdubai.com/tour/dubai-iconic-places-tour"><u style="text-decoration-color: ; text-decoration-style: ; text-decoration-thickness: ; text-underline-offset: ">Dubai'de gezilecek harika yerlerden</u></a> biri.</p>
<p>Burasını daha da cazip kılan şey ise ulaşılabilirliği ve fiyat-performans oranı. Dubai'ye gitmek pahalı mı diye merak ediyorsanız, aslında değil. <a target="_blank" rel="noopener" href="https://guideofdubai.com/tour/dubai-iconic-places-tour"><u style="text-decoration-color: ; text-decoration-style: ; text-decoration-thickness: ; text-underline-offset: ">Dubai'de ücretsiz gezilecek yerler</u></a> ve The View Palm gibi makul fiyatlı deneyimler, şehri ziyaretçiler için oldukça uygun kılıyor.</p>
<h3>Aileler ve Her Yaş İçin İdeal</h3>
<p>Aile gezisi planlıyorsanız, <a target="_blank" rel="noopener" href="https://www.theviewpalm.ae/?utm_source=GMBlisting&amp;utm_medium=organic&amp;utm_campaign=gmb"><u style="text-decoration-color: ; text-decoration-style: ; text-decoration-thickness: ; text-underline-offset: ">The View Palm</u></a> herkes için güvenli ve heyecan verici bir ortam sunuyor. <a target="_blank" rel="noopener" href="https://guideofdubai.com/tour/dubai-iconic-places-tour"><u style="text-decoration-color: ; text-decoration-style: ; text-decoration-thickness: ; text-underline-offset: ">Aileyle Dubai'de gezilecek en iyi yerlerden</u></a> biri olarak, interaktif ekranlar, hediyelik eşya dükkanı ve manzarayı izleyebileceğiniz kafeler içeriyor.</p>
<p>Dubai'yi ziyaret etmek için en iyi ay hangisi diye soranlar için, Kasım ve Mart arasındaki serin aylar, bu tür açık hava seyir noktalarını en konforlu şekilde deneyimlemenizi sağlar.</p>
<div data-instagram-carousel="" data-cards="[{&quot;imageUrl&quot;:&quot;https://assets.guideofdubai.com/uploads/1.jpg-cdLcOu.jpg&quot;,&quot;username&quot;:&quot;Guide Of Dubai&quot;,&quot;userProfileImage&quot;:&quot;https://assets.guideofdubai.com/uploads/guideofdubai-instagram.jpg-ylIblY.jpg&quot;,&quot;postUrl&quot;:&quot;https://www.instagram.com/p/DH5soRbI2xn/?img_index=1&quot;,&quot;caption&quot;:&quot;Dubai'nin muhteşem manzaralarını yukarıdan keşfetmeye hazır mısınız? 🚁✨ Büyüleyici bir Dubai helikopter turu deneyimleyin!&quot;,&quot;likesCount&quot;:0,&quot;location&quot;:&quot;&quot;,&quot;timestamp&quot;:&quot;5 Mayıs 2025&quot;}]" ></div>
<h3>The View Palm Dubai'nin Değerini Kanıtlıyor</h3>
<p>Hâlâ Dubai'ye gitmeye değer mi diye mi düşünüyorsunuz? 240 metre yükseklikte, şehir silüetinin üzerinde güneşin batışını izlediğinizi ve gerçekten benzersiz bir deneyim yaşadığınızı hayal edin. Sadece bu an bile sorunun cevabını veriyor.</p>
<p>Buna Dubai'nin lüks ama ulaşılabilir cazibe merkezleri sunma konusundaki kararlılığını da ekleyin ve neden deneyimli gezginler tarafından Dubai'nin en iyi ziyaret ayları arasında gösterildiğini anlayacaksınız. Ultra-modern kulelerden huzurlu kıyı noktalarına kadar Dubai, zıtlıkları mükemmel bir dengeyle birleştiriyor.</p>
<h3>Dubai'de Daha Fazla Gezilecek Yer Keşfedin</h3>
<p><a target="_blank" rel="noopener" href="https://www.theviewpalm.ae/?utm_source=GMBlisting&amp;utm_medium=organic&amp;utm_campaign=gmb"><u style="text-decoration-color: ; text-decoration-style: ; text-decoration-thickness: ; text-underline-offset: ">The View Palm</u></a>'ı ziyaret ettikten sonra keşfetmeye devam etmek istemez misiniz? Şehirde gezilecek daha birçok yer var, örneğin:</p>
<ul>
  <li><p><a target="_blank" rel="noopener" href="https://guideofdubai.com/ticket/burj-khalifa-at-the-top-level-125-124"><u style="text-decoration-color: ; text-decoration-style: ; text-decoration-thickness: ; text-underline-offset: ">Burj Khalifa</u></a></p></li>
  <li><p>Dubai Marina Yürüyüş Yolu</p></li>
  <li><p>Al Fahidi Tarihi Mahallesi</p></li>
  <li><p><a target="_blank" rel="noopener" href="https://guideofdubai.com/ticket/dubai-frame"><u style="text-decoration-color: ; text-decoration-style: ; text-decoration-thickness: ; text-underline-offset: ">Dubai Frame</u></a></p></li>
</ul>
<p>Bu noktalar, Dubai'nin tarihi ve ultra-modern yönlerini bir arada sunuyor.</p>
<h3>Dubai'yi Ziyaret Etmek İçin En İyi Zaman Ne Zaman?</h3>
<p>Dubai'yi ziyaret etmek için en iyi zamanı seçmek, seyahatinizi daha da özel kılar. Yaz ayları sıcak geçse de, kış sezonu seyir teraslarını ve <a target="_blank" rel="noopener" href="https://guideofdubai.com/tour/dubai-iconic-places-tour"><u style="text-decoration-color: ; text-decoration-style: ; text-decoration-thickness: ; text-underline-offset: ">aileyle gezilecek yerleri</u></a> keşfetmek için idealdir. Aralık-Şubat arası genellikle Dubai'yi ziyaret etmek için en iyi aylar olarak kabul edilir.</p>
<h3>Dubai'ye Gitmeye Değer mi?</h3>
<p>Kesinlikle evet. İkonik silüetinden The View Palm'dan izlenen büyüleyici gün batımlarına kadar Dubai, unutulmaz anlar sunuyor. İster ilk kez gelin, ister tekrar ziyaret edin, her deneyim şehrin büyüsüne yeni bir katman ekliyor.</p>
<h3>Seyahatinizi Şimdi Planlayın</h3>
<p>Dubai'ye gitmeye değer mi? Kesinlikle. Yolculuğunuza <a target="_blank" rel="noopener" href="https://www.theviewpalm.ae/?utm_source=GMBlisting&amp;utm_medium=organic&amp;utm_campaign=gmb"><u style="text-decoration-color: ; text-decoration-style: ; text-decoration-thickness: ; text-underline-offset: ">The View Palm</u></a> ile başlayın ve milyonlarca insanın bu eşsiz şehre neden hayran kaldığını keşfedin. Dubai'yi şimdi keşfedin ve seyahat hikayenizi unutulmaz kılın.</p>
`;

export default DummyText;
